apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      version: 0.0.30
      sourceRef:
        kind: HelmRepository
        name: rancher-lpp
        namespace: flux-system
  values:
    storageClass:
      name: local-path
      defaultClass: true