apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      # sem version -> pega uma estável do repo
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    addressPools:
      - name: homelab-pool
        protocol: layer2
        addresses:
          - 192.168.86.240-192.168.86.250
    l2Advertisements:
      - name: homelab-l2
        ipAddressPools:
          - homelab-pool
