apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      # sem version -> pega uma estável do repo
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  # o CRD e control plane sobem; o pool vai no arquivo abaixo